name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX and compile DevelopmentPlan
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "DevelopmentPlan/DevelopmentPlan.tex" # Adjust to your root .tex file

      - name: Move PDFs for DevelopmentPlan
        run: |
          mkdir -p DevelopmentPlan/pdf
          mv DevelopmentPlan/*.pdf DevelopmentPlan/pdf/

      - name: Set up LaTeX and compile HazardAnalysis
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "HazardAnalysis/HazardAnalysis.tex" # Adjust to your root .tex file

      - name: Move PDFs for HazardAnalysis
        run: |
          mkdir -p HazardAnalysis/pdf
          mv HazardAnalysis/*.pdf HazardAnalysis/pdf/

      - name: Set up LaTeX and compile ProblemStatementAndGoals
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "ProblemStatementAndGoals/ProblemStatement.tex" # Adjust to your root .tex file

      - name: Move PDFs for ProblemStatementAndGoals
        run: |
          mkdir -p ProblemStatementAndGoals/pdf
          mv ProblemStatementAndGoals/*.pdf ProblemStatementAndGoals/pdf/
