name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX and compile DevelopmentPlan
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "docs/DevelopmentPlan/DevelopmentPlan.tex" # Adjust to your root .tex file

      - name: Set up LaTeX and compile HazardAnalysis
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "docs/HazardAnalysis/HazardAnalysis.tex" # Adjust to your root .tex file

      - name: Set up LaTeX and compile ProblemStatementAndGoals
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "docs/ProblemStatementAndGoals/ProblemStatement.tex" # Adjust to your root .tex file
