name: Remove Committed PDFs

on:
  push:
    branches:
      - "**" # Trigger on pushes to all branches

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the full history to ensure all commits are available

      # Step 2: Find and remove committed PDFs
      - name: Remove committed PDFs
        run: |
          # Find committed PDF files in the current branch
          git ls-tree -r --name-only HEAD | grep '\.pdf$' || echo "No PDFs found"

          # Remove found PDFs from Git tracking
          git ls-tree -r --name-only HEAD | grep '\.pdf$' | xargs -r git rm --cached

          # Commit the changes (if any)
          git commit -m "Remove committed PDFs from this branch" || echo "No changes to commit"

      # Step 3: Push changes to the current branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
