name: Run Frontend Unit Tests

on: [push, pull_request]

jobs:
  coverage:
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v3
    - uses: ArtiomTr/jest-coverage-report-action@v2
    with:
      working-directory: ./src/frontend
      github-token: ${{ secrets.GITHUB_TOKEN }}